-- MySQL Script generated by MySQL Workbench
-- 12/10/15 11:14:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `pwd` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `age` INT NOT NULL,
  `sex` VARCHAR(1) NOT NULL,
  `dateinscription` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Questionnaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Questionnaire` (
  `IdQuestionnaire` INT NOT NULL AUTO_INCREMENT,
  `IdUser` INT NOT NULL,
  `Libelle` VARCHAR(100) NOT NULL,
  `Prive` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdQuestionnaire`),
  CONSTRAINT `id_customer`
    FOREIGN KEY (`IdUser`)
    REFERENCES `customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `IdQuestionnaire_UNIQUE` ON `Questionnaire` (`IdQuestionnaire` ASC);

CREATE INDEX `id_idx` ON `Questionnaire` (`IdUser` ASC);


-- -----------------------------------------------------
-- Table `ParamTypeQuestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ParamTypeQuestion` (
  `IdType` INT NOT NULL AUTO_INCREMENT,
  `Libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdType`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idType_UNIQUE` ON `ParamTypeQuestion` (`IdType` ASC);

CREATE UNIQUE INDEX `Libelle_UNIQUE` ON `ParamTypeQuestion` (`Libelle` ASC);


-- -----------------------------------------------------
-- Table `Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Question` (
  `IdQuestion` INT NOT NULL AUTO_INCREMENT,
  `IdQuestionnaire` INT NOT NULL,
  `Libelle` VARCHAR(450) NOT NULL,
  `IdType` INT NOT NULL,
  PRIMARY KEY (`IdQuestion`),
  CONSTRAINT `Id_Questionnaire`
    FOREIGN KEY (`IdQuestionnaire`)
    REFERENCES `Questionnaire` (`IdQuestionnaire`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `Id_Type`
    FOREIGN KEY (`IdType`)
    REFERENCES `ParamTypeQuestion` (`IdType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `IdQuestion_UNIQUE` ON `Question` (`IdQuestion` ASC);

CREATE INDEX `IdQuestionnaire_idx` ON `Question` (`IdQuestionnaire` ASC);

CREATE INDEX `IdType_idx` ON `Question` (`IdType` ASC);


-- -----------------------------------------------------
-- Table `ReponseQCM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReponseQCM` (
  `idReponseQCM` INT NOT NULL AUTO_INCREMENT,
  `IdQuestion` INT NOT NULL,
  `Libelle` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idReponseQCM`),
  CONSTRAINT `Id_Question`
    FOREIGN KEY (`IdQuestion`)
    REFERENCES `Question` (`IdQuestion`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `IdQuestion_idx` ON `ReponseQCM` (`IdQuestion` ASC);


-- -----------------------------------------------------
-- Table `FormulaireReponses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FormulaireReponses` (
  `idFormulaire` INT NOT NULL AUTO_INCREMENT,
  `IdUser` INT NULL,
  `IdQuestionnaire` INT NOT NULL,
  PRIMARY KEY (`idFormulaire`),
  CONSTRAINT `Id_Questionnaire_Reponse`
    FOREIGN KEY (`IdQuestionnaire`)
    REFERENCES `Questionnaire` (`IdQuestionnaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_User`
    FOREIGN KEY (`IdUser`)
    REFERENCES `customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idFormulaire_UNIQUE` ON `FormulaireReponses` (`idFormulaire` ASC);

CREATE INDEX `IdQuestionnaire_idx` ON `FormulaireReponses` (`IdQuestionnaire` ASC);

CREATE INDEX `idUser_idx` ON `FormulaireReponses` (`IdUser` ASC);


-- -----------------------------------------------------
-- Table `Reponse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reponse` (
  `IdReponse` INT NOT NULL AUTO_INCREMENT,
  `IdFormulaire` INT NOT NULL,
  `IdQuestion` INT NOT NULL,
  `Reponse` VARCHAR(100) NULL,
  `IdReponseQCM` INT NULL,
  PRIMARY KEY (`IdReponse`),
  CONSTRAINT `Id_Question_Reponse`
    FOREIGN KEY (`IdQuestion`)
    REFERENCES `Question` (`IdQuestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Id_Reponse_QCM`
    FOREIGN KEY (`IdReponseQCM`)
    REFERENCES `ReponseQCM` (`idReponseQCM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Id_Formulaire`
    FOREIGN KEY (`IdFormulaire`)
    REFERENCES `FormulaireReponses` (`idFormulaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `IdQuestion_idx` ON `Reponse` (`IdQuestion` ASC);

CREATE INDEX `IdReponseQCM_idx` ON `Reponse` (`IdReponseQCM` ASC);

CREATE INDEX `IdFormulaire_idx` ON `Reponse` (`IdFormulaire` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
