-- MySQL Script generated by MySQL Workbench
-- 12/10/15 07:50:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `pwd` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `age` INT NOT NULL,
  `sex` VARCHAR(1) NOT NULL,
  `dateinscription` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Questionnaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Questionnaire` (
  `IdQuestionnaire` INT NOT NULL AUTO_INCREMENT,
  `IdUser` INT NOT NULL,
  `Libelle` VARCHAR(100) NOT NULL,
  `Public` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdQuestionnaire`),
  CONSTRAINT `id`
    FOREIGN KEY (`IdUser`)
    REFERENCES `mydb`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `IdQuestionnaire_UNIQUE` ON `mydb`.`Questionnaire` (`IdQuestionnaire` ASC);

CREATE INDEX `id_idx` ON `mydb`.`Questionnaire` (`IdUser` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`ParamTypeQuestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ParamTypeQuestion` (
  `IdType` INT NOT NULL AUTO_INCREMENT,
  `Libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdType`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idType_UNIQUE` ON `mydb`.`ParamTypeQuestion` (`IdType` ASC);

CREATE UNIQUE INDEX `Libelle_UNIQUE` ON `mydb`.`ParamTypeQuestion` (`Libelle` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Question` (
  `IdQuestion` INT NOT NULL AUTO_INCREMENT,
  `IdQuestionnaire` INT NOT NULL,
  `Libelle` VARCHAR(450) NOT NULL,
  `IdType` INT NOT NULL,
  PRIMARY KEY (`IdQuestion`),
  CONSTRAINT `IdQuestionnaire`
    FOREIGN KEY (`IdQuestionnaire`)
    REFERENCES `mydb`.`Questionnaire` (`IdQuestionnaire`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `IdType`
    FOREIGN KEY (`IdType`)
    REFERENCES `mydb`.`ParamTypeQuestion` (`IdType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `IdQuestion_UNIQUE` ON `mydb`.`Question` (`IdQuestion` ASC);

CREATE INDEX `IdQuestionnaire_idx` ON `mydb`.`Question` (`IdQuestionnaire` ASC);

CREATE INDEX `IdType_idx` ON `mydb`.`Question` (`IdType` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`ReponseQCM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ReponseQCM` (
  `idReponseQCM` INT NOT NULL AUTO_INCREMENT,
  `IdQuestion` INT NOT NULL,
  `Libelle` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idReponseQCM`),
  CONSTRAINT `IdQuestion`
    FOREIGN KEY (`IdQuestion`)
    REFERENCES `mydb`.`Question` (`IdQuestion`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `IdQuestion_idx` ON `mydb`.`ReponseQCM` (`IdQuestion` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`FormulaireReponses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FormulaireReponses` (
  `idFormulaire` INT NOT NULL AUTO_INCREMENT,
  `IdUser` INT NULL,
  `IdQuestionnaire` INT NOT NULL,
  PRIMARY KEY (`idFormulaire`),
  CONSTRAINT `IdQuestionnaire`
    FOREIGN KEY (`IdQuestionnaire`)
    REFERENCES `mydb`.`Questionnaire` (`IdQuestionnaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUser`
    FOREIGN KEY (`IdUser`)
    REFERENCES `mydb`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idFormulaire_UNIQUE` ON `mydb`.`FormulaireReponses` (`idFormulaire` ASC);

CREATE INDEX `IdQuestionnaire_idx` ON `mydb`.`FormulaireReponses` (`IdQuestionnaire` ASC);

CREATE INDEX `idUser_idx` ON `mydb`.`FormulaireReponses` (`IdUser` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Reponse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reponse` (
  `IdReponse` INT NOT NULL AUTO_INCREMENT,
  `IdFormulaire` INT NOT NULL,
  `IdQuestion` INT NOT NULL,
  `Reponse` VARCHAR(100) NULL,
  `IdReponseQCM` INT NULL,
  PRIMARY KEY (`IdReponse`),
  CONSTRAINT `IdQuestion`
    FOREIGN KEY (`IdQuestion`)
    REFERENCES `mydb`.`Question` (`IdQuestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdReponseQCM`
    FOREIGN KEY (`IdReponseQCM`)
    REFERENCES `mydb`.`ReponseQCM` (`idReponseQCM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdFormulaire`
    FOREIGN KEY (`IdFormulaire`)
    REFERENCES `mydb`.`FormulaireReponses` (`idFormulaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `IdQuestion_idx` ON `mydb`.`Reponse` (`IdQuestion` ASC);

CREATE INDEX `IdReponseQCM_idx` ON `mydb`.`Reponse` (`IdReponseQCM` ASC);

CREATE INDEX `IdFormulaire_idx` ON `mydb`.`Reponse` (`IdFormulaire` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
